### ISSUE TITLE
Remove confusing 'available' concept from MCP servers in favor of unified service management

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#112]
# Problem Statement

The current `mcpserver_available` tool and `Available` field in MCP server responses create confusion and redundancy in the user experience. Currently:

1. **Confusing semantics**: `mcpserver_available` only checks if a definition exists, not if the service is actually running and tools are accessible
2. **Redundant functionality**: We already have comprehensive service management via `core_service_status` that provides richer information
3. **Poor UX**: Users need to understand two different concepts (availability vs service state) when one would suffice
4. **Bug-prone**: The current implementation reports `available: true` even when the MCP server service is stopped

## Current Confusing Behavior

```yaml
# User stops an MCP server
- tool: "core_service_stop"
  args: { name: "my-server" }

# But availability still reports true (CONFUSING!)
- tool: "core_mcpserver_available" 
  args: { name: "my-server" }
  result: { available: true }  # ❌ Misleading

# While service status correctly shows stopped
- tool: "core_service_status"
  args: { name: "my-server" }  
  result: { state: "stopped", health: "unknown" }  # ✅ Clear
```

## Proposed Solution

**Remove the `available` concept entirely** and direct users to the unified service management system:

### What Gets Removed
- `core_mcpserver_available` tool
- `mcpserver_available` internal tool 
- `Available` field from `MCPServerInfo` API responses
- `IsAvailable()` method from `MCPServerManager`
- Related test scenarios using availability checks

### What Users Should Use Instead
- **`core_service_status`** - Get comprehensive service state, health, and error information
- **`core_service_list`** - List all services including MCP servers
- **Aggregator tool availability** - Check if specific tools are accessible via aggregator

## Benefits

1. **🎯 Better UX**: One clear mental model (service management) instead of two confusing concepts
2. **📊 Richer Information**: Service status provides state, health, errors vs. just boolean availability
3. **🧹 Less Maintenance**: Eliminate redundant API surface and associated bugs
4. **🏗️ Cleaner Architecture**: Tool availability is aggregator's responsibility, service state is orchestrator's responsibility
5. **🔄 Consistency**: All services (MCP servers, aggregator, etc.) managed through same interface

### Phase 1: Remove Code
- [ ] Remove `mcpserver_available` tool from `internal/mcpserver/api_adapter.go`
- [ ] Remove `Available` field from `MCPServerInfo` in `internal/api/types.go`
- [ ] Remove `IsAvailable()` method from `MCPServerManager`
- [ ] Remove `IsMCPServerAvailable()` from MCP server API adapter
- [ ] Update `GetMCPServer()` to not include `Available` field

### Phase 2: Update Tests
- [ ] Update `mcpserver-check-available.yaml` to use `core_service_status`
- [ ] Update `mcpserver-check-unavailable.yaml` to use `core_service_status`
- [ ] Update `mcpserver-tool-availability-lifecycle.yaml` to use `core_service_status`
- [ ] Update `mcpserver-lifecycle.yaml` availability checks
- [ ] Fix any other test scenarios using `core_mcpserver_available`

### Phase 3: Update CLI & Schema
- [ ] Update `cmd/check.go` mapping from `core_mcpserver_available` to `core_service_status`
- [ ] Remove `core_mcpserver_available` from JSON schema
- [ ] Update any documentation references

### Phase 4: Testing
- [ ] Run full test suite to ensure no regressions
- [ ] Test CLI `envctl check mcpserver` functionality
- [ ] Verify service management works for MCP servers

### For API Users
**Before:**
```bash
envctl check mcpserver my-server
# Uses core_mcpserver_available internally
```

**After:**
```bash  
envctl service status my-server
# Uses core_service_status - provides richer information
```

### For Test Scenarios
**Before:**
```yaml
- tool: "core_mcpserver_available"
  args: { name: "server" }
  expected: { available: true }
```

**After:**
```yaml
- tool: "core_service_status"  
  args: { name: "server" }
  expected: { state: "running", health: "healthy" }
```

## Alternative Considered

We considered making `mcpserver_available` check actual service state + tool availability through the aggregator, but this:
- Adds complexity and circular dependencies
- Still maintains confusing dual concepts
- Provides less useful information than service status
- Doesn't align with the architectural principle of unified service management

## Related Issues

This addresses the failing test in `mcpserver-tool-availability-lifecycle.yaml` where availability doesn't reflect actual service state, and improves overall UX consistency across the platform.
