### ISSUE TITLE
Implement workflow storage and persistence

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#51]
## Overview
Implement a storage system for managing workflow definitions with support for both user-defined and agent-created workflows. This includes file-based persistence and change notifications.

## Description
Create a workflow storage manager that:
- Loads workflows from YAML files
- Maintains separate files for user and agent workflows
- Supports CRUD operations
- Provides change notifications for hot-reload
- Enforces permission controls (agentModifiable flag)

### 1. Create `internal/workflow/storage.go`:

```go
package workflow

import (
    "fmt"
    "os"
    "path/filepath"
    "sync"
    "time"
    
    "gopkg.in/yaml.v3"
    "envctl/pkg/logging"
    "envctl/internal/config"
)

// WorkflowStorage manages persistent storage of workflows
type WorkflowStorage struct {
    mu           sync.RWMutex
    userFile     string // User-defined workflows (read-only for agents)
    agentFile    string // Agent-created workflows
    workflows    map[string]*config.WorkflowDefinition
    changeNotify chan struct{} // Notify aggregator of changes
}

// NewWorkflowStorage creates a new workflow storage manager
func NewWorkflowStorage(configDir string) (*WorkflowStorage, error)

// LoadWorkflows loads workflows from both user and agent files
func (ws *WorkflowStorage) LoadWorkflows() error

// GetWorkflow retrieves a workflow by name
func (ws *WorkflowStorage) GetWorkflow(name string) (*config.WorkflowDefinition, error)

// ListWorkflows returns all workflows
func (ws *WorkflowStorage) ListWorkflows() []config.WorkflowDefinition

// CreateWorkflow creates a new agent workflow
func (ws *WorkflowStorage) CreateWorkflow(workflow config.WorkflowDefinition) error

// UpdateWorkflow updates an existing workflow
func (ws *WorkflowStorage) UpdateWorkflow(name string, updates config.WorkflowDefinition) error

// DeleteWorkflow deletes a workflow
func (ws *WorkflowStorage) DeleteWorkflow(name string) error

// GetChangeChannel returns a channel that notifies of workflow changes
func (ws *WorkflowStorage) GetChangeChannel() <-chan struct{}
```

### 2. Key implementation points:

- **File Structure**:
  - `~/.envctl/workflows.yaml` - User workflows (read-only for agents)
  - `~/.envctl/agent_workflows.yaml` - Agent-created workflows

- **Permission Model**:
  - User workflows: `agentModifiable: false` by default
  - Agent workflows: `agentModifiable: true` always
  - Only workflows with `agentModifiable: true` can be updated/deleted by agents

- **Atomic File Operations**:
  - Write to temp file first
  - Use atomic rename to prevent corruption
  - Proper error handling and rollback

- **Change Notifications**:
  - Non-blocking channel for notifying aggregator
  - Supports hot-reload of workflows

### 3. Example workflow files:

**User workflows** (`~/.envctl/workflows.yaml`):
```yaml
workflows:
  - name: connect_cluster
    description: "Connect to a specific Teleport cluster"
    icon: "🔌"
    agentModifiable: false
    inputSchema:
      type: object
      properties:
        cluster:
          type: string
          description: "Exact cluster name"
      required: ["cluster"]
    steps:
      - id: login
        tool: teleport_kube
        args:
          command: "login"
          cluster: "{{.cluster}}"
```

**Agent workflows** (`~/.envctl/agent_workflows.yaml`):
```yaml
workflows:
  - name: custom_diagnostics
    description: "Custom diagnostics workflow"
    icon: "🔍"
    agentModifiable: true
    createdBy: "agent"
    createdAt: "2024-01-10T10:00:00Z"
    version: 1
    inputSchema:
      type: object
    steps:
      - id: check_pods
        tool: kubectl_get
        args:
          resourceType: "pods"
```

## Acceptance Criteria
- [ ] WorkflowStorage implementation with all CRUD methods
- [ ] Separate file handling for user and agent workflows
- [ ] Atomic file operations to prevent corruption
- [ ] Permission enforcement based on agentModifiable flag
- [ ] Change notification system for hot-reload
- [ ] Proper error handling and validation
- [ ] Unit tests covering all operations
- [ ] Integration tests for file operations

## Dependencies
- #50 - Workflow types and configuration structures

## Testing Requirements
- Unit tests for all CRUD operations
- Tests for concurrent access
- Tests for file corruption scenarios
- Tests for permission enforcement
- Tests for change notifications

## Labels
- enhancement
- workflow
- storage
