### ISSUE TITLE
Implement workflow management MCP tools

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#54]
## Overview
Create MCP tools that allow agents to manage workflows - list, get, create, update, and delete workflows programmatically.

## Description
Implement a set of workflow management tools that:
- Allow agents to discover available workflows
- Enable creation of new workflows
- Support updating agent-modifiable workflows
- Provide deletion of agent-created workflows
- Include validation of workflow definitions

### 1. Create `internal/workflow/management_tools.go`:

```go
package workflow

import (
    "context"
    "encoding/json"
    "fmt"
    
    "envctl/internal/config"
    "github.com/mark3labs/mcp-go/mcp"
    "github.com/mark3labs/mcp-go/server"
)

// ManagementTools provides MCP tools for workflow CRUD operations
type ManagementTools struct {
    storage *WorkflowStorage
}

// NewManagementTools creates management tools
func NewManagementTools(storage *WorkflowStorage) *ManagementTools

// GetTools returns all workflow management tools as MCP ServerTools
func (mt *ManagementTools) GetTools() []server.ServerTool
```

#### `workflow.list`
```yaml
name: workflow.list
description: List all available workflows and their modification permissions
inputSchema:
  type: object
  properties:
    modifiable_only:
      type: boolean
      description: Only show workflows that can be modified by agents
    include_steps:
      type: boolean
      description: Include workflow steps in the response
      default: false
```

#### `workflow.get`
```yaml
name: workflow.get  
description: Get detailed information about a specific workflow
inputSchema:
  type: object
  properties:
    name:
      type: string
      description: Name of the workflow to retrieve
  required: ["name"]
```

#### `workflow.create`
```yaml
name: workflow.create
description: Create a new workflow that sequences multiple tool calls
annotations:
  destructiveHint: true
inputSchema:
  type: object
  properties:
    name:
      type: string
      description: Unique name for the workflow (alphanumeric with underscores)
      pattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
    description:
      type: string
      description: Description of what the workflow does
    icon:
      type: string
      description: Optional emoji icon for the workflow
    input_schema:
      type: object
      description: Schema for workflow inputs (YAML format)
    steps:
      type: array
      description: Sequence of tool calls to execute
      items:
        type: object
        properties:
          id:
            type: string
            description: Unique identifier for this step
          tool:
            type: string
            description: Tool name to call (must exist in aggregator)
          args:
            type: object
            description: Arguments for the tool (supports {{expressions}})
          store:
            type: string
            description: Optional key to store result
        required: ["id", "tool", "args"]
  required: ["name", "description", "steps"]
```

#### `workflow.update`
```yaml
name: workflow.update
description: Update an existing workflow (only agent-modifiable workflows)
annotations:
  destructiveHint: true
inputSchema:
  type: object
  properties:
    name:
      type: string
      description: Name of the workflow to update
    updates:
      type: object
      description: Fields to update (same structure as create)
  required: ["name", "updates"]
```

#### `workflow.delete`
```yaml
name: workflow.delete
description: Delete a workflow (only agent-modifiable workflows)
annotations:
  destructiveHint: true
inputSchema:
  type: object
  properties:
    name:
      type: string
      description: Name of the workflow to delete
  required: ["name"]
```

#### `workflow.validate`
```yaml
name: workflow.validate
description: Validate a workflow definition without creating it
inputSchema:
  type: object
  properties:
    workflow:
      type: object
      description: Workflow definition to validate
  required: ["workflow"]
```

### 3. Implementation example for create tool:

```go
func (mt *ManagementTools) createCreateWorkflowTool() server.ServerTool {
    return server.ServerTool{
        Tool: mcp.Tool{
            Name:        "workflow.create",
            Description: "Create a new workflow that sequences multiple tool calls",
            Annotations: map[string]interface{}{
                "destructiveHint": true,
            },
            InputSchema: // ... schema from above
        },
        Handler: func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
            args, _ := req.Params.Arguments.(map[string]interface{})
            
            // Parse and validate workflow
            workflow := config.WorkflowDefinition{
                Name:            getString(args, "name"),
                Description:     getString(args, "description"),
                Icon:            getString(args, "icon"),
                AgentModifiable: true, // Agent-created workflows are always modifiable
            }
            
            // Parse input schema
            if schema, ok := args["input_schema"].(map[string]interface{}); ok {
                workflow.InputSchema = parseInputSchema(schema)
            }
            
            // Parse steps
            if steps, ok := args["steps"].([]interface{}); ok {
                workflow.Steps = parseSteps(steps)
            }
            
            // Validate workflow
            if err := validateWorkflow(workflow); err != nil {
                return nil, err
            }
            
            // Create workflow
            if err := mt.storage.CreateWorkflow(workflow); err != nil {
                return nil, err
            }
            
            return &mcp.CallToolResult{
                Content: []mcp.Content{{
                    Type: "text",
                    Text: fmt.Sprintf("Successfully created workflow '%s' with %d steps", 
                        workflow.Name, len(workflow.Steps)),
                }},
            }, nil
        },
    }
}
```

### 4. Validation requirements:

- Workflow names must be unique
- Workflow names must match pattern `^[a-zA-Z][a-zA-Z0-9_]*$`
- All referenced tools must exist in the aggregator
- Step IDs must be unique within a workflow
- Input schema must be valid YAML
- Template syntax in arguments must be valid

## Acceptance Criteria
- [ ] All management tools implemented (list, get, create, update, delete, validate)
- [ ] Proper permission checking (agentModifiable flag)
- [ ] Workflow validation before create/update
- [ ] Clear error messages for validation failures
- [ ] Unit tests for all tool handlers
- [ ] Integration tests with storage layer
- [ ] Example usage documentation

## Dependencies
- #50 - Workflow types and configuration structures
- #51 - Workflow storage implementation

## Testing Requirements
- Unit tests for each management tool
- Tests for permission enforcement
- Tests for workflow validation
- Tests for error scenarios
- Integration tests with real storage

## Labels
- enhancement
- workflow
- tools
