### ISSUE TITLE
Add workflow documentation and examples

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#55]
## Overview
Create comprehensive documentation for the workflow system, including user guides, developer documentation, and example workflows.

## Description
Document the workflow feature with:
- User guide for creating and using workflows
- Developer guide for extending the system
- Example workflows for common use cases
- Integration with existing envctl documentation

### 1. Update main README.md

Add a section about workflows:

```markdown
## Workflows

envctl supports defining reusable sequences of tool calls as workflows. This allows you to:
- Automate complex multi-step operations
- Share common patterns across teams
- Let AI agents create and improve their own workflows

### Quick Example

```yaml
# ~/.envctl/workflows.yaml
workflows:
  - name: connect_cluster
    description: "Connect to a Teleport cluster"
    inputSchema:
      type: object
      properties:
        cluster:
          type: string
      required: ["cluster"]
    steps:
      - id: login
        tool: teleport_kube
        args:
          command: "login"
          cluster: "{{.cluster}}"
```

Use via MCP client:
```
workflow.connect_cluster({"cluster": "mymc-cluster1"})
```

See [Workflow Documentation](docs/workflows.md) for details.
```

### 2. Create `docs/workflows.md`

Comprehensive workflow documentation covering:

- **Introduction**
  - What are workflows
  - Benefits and use cases
  - Architecture overview

- **User Guide**
  - Creating workflows
  - Workflow syntax
  - Template variables
  - Input schemas
  - Example workflows

- **Agent Usage**
  - Discovering workflows
  - Creating workflows programmatically
  - Modifying existing workflows
  - Best practices

- **Reference**
  - Workflow schema
  - Management tools
  - Configuration options

### 3. Create `docs/examples/workflows/`

Example workflow files:

#### `basic_workflows.yaml`
```yaml
workflows:
  # Simple cluster connection
  - name: connect_cluster
    description: "Connect to a specific Teleport cluster"
    icon: "🔌"
    agentModifiable: false
    inputSchema:
      type: object
      properties:
        cluster:
          type: string
          description: "Exact cluster name to connect to"
      required: ["cluster"]
    steps:
      - id: login
        tool: teleport_kube
        args:
          command: "login"
          cluster: "{{.cluster}}"
        store: login_result
      
      - id: get_context
        tool: kubectl_context
        args:
          operation: "get"
        store: context

  # List available clusters
  - name: search_clusters
    description: "Search for available Teleport clusters"
    icon: "🔍"
    agentModifiable: false
    inputSchema:
      type: object
      properties:
        pattern:
          type: string
          description: "Pattern to filter clusters (optional)"
          default: ""
    steps:
      - id: list_all
        tool: teleport_kube
        args:
          command: "ls"
        store: clusters
```

#### `monitoring_workflows.yaml`
```yaml
workflows:
  # Set up Prometheus monitoring
  - name: setup_prometheus
    description: "Set up Prometheus port forwarding for the current cluster"
    icon: "📊"
    agentModifiable: false
    inputSchema:
      type: object
      properties:
        namespace:
          type: string
          description: "Namespace where Prometheus is installed"
          default: "monitoring"
        local_port:
          type: integer
          description: "Local port for Prometheus"
          default: 9090
    steps:
      - id: forward_prometheus
        tool: port_forward
        args:
          resourceType: "service"
          resourceName: "prometheus-server"
          namespace: "{{.namespace}}"
          localPort: "{{.local_port}}"
          targetPort: 9090
        store: port_forward_info
  
  # Set up full monitoring stack
  - name: setup_monitoring_stack
    description: "Set up port forwarding for Prometheus and Grafana"
    icon: "📈"
    agentModifiable: true
    inputSchema:
      type: object
      properties:
        prometheus_port:
          type: integer
          default: 9090
        grafana_port:
          type: integer
          default: 3000
    steps:
      - id: forward_prometheus
        tool: port_forward
        args:
          resourceType: "service"
          resourceName: "prometheus-server"
          namespace: "monitoring"
          localPort: "{{.prometheus_port}}"
          targetPort: 9090
        store: prometheus
        
      - id: forward_grafana
        tool: port_forward
        args:
          resourceType: "service"
          resourceName: "grafana"
          namespace: "monitoring"
          localPort: "{{.grafana_port}}"
          targetPort: 3000
        store: grafana
```

#### `diagnostic_workflows.yaml`
```yaml
workflows:
  # Quick cluster health check
  - name: cluster_health_check
    description: "Run quick diagnostics on current cluster"
    icon: "🏥"
    agentModifiable: true
    inputSchema:
      type: object
    steps:
      - id: check_nodes
        tool: kubectl_get
        args:
          resourceType: "nodes"
          output: "json"
        store: nodes
        
      - id: check_pods
        tool: kubectl_get
        args:
          resourceType: "pods"
          allNamespaces: true
          output: "json"
        store: pods
        
      - id: check_events
        tool: kubectl_get
        args:
          resourceType: "events"
          allNamespaces: true
          sortBy: "lastTimestamp"
        store: events

  # Namespace diagnostics
  - name: namespace_diagnostics
    description: "Get detailed information about a namespace"
    icon: "🔍"
    agentModifiable: true
    inputSchema:
      type: object
      properties:
        namespace:
          type: string
          description: "Namespace to diagnose"
          default: "default"
    steps:
      - id: get_pods
        tool: kubectl_get
        args:
          resourceType: "pods"
          namespace: "{{.namespace}}"
        store: pods
        
      - id: get_services
        tool: kubectl_get
        args:
          resourceType: "services"
          namespace: "{{.namespace}}"
        store: services
        
      - id: get_events
        tool: kubectl_get
        args:
          resourceType: "events"
          namespace: "{{.namespace}}"
        store: events
```

### 4. Create `internal/workflow/doc.go`

Package documentation:

```go
/*
Package workflow implements a system for defining and executing sequences of MCP tool calls.

The workflow system allows users and agents to create reusable automation patterns that combine
multiple tool calls into a single operation. Workflows are exposed as standard MCP tools through
the aggregator, making them indistinguishable from native tools to MCP clients.

# Architecture

The workflow system consists of several components:

  - Storage: Manages persistence of workflow definitions in YAML files
  - Executor: Runs workflow steps sequentially with template resolution
  - Manager: Integrates workflows with the aggregator
  - Management Tools: MCP tools for CRUD operations on workflows

# Workflow Definition

Workflows are defined in YAML with the following structure:

	workflows:
	  - name: example_workflow
	    description: "Example workflow"
	    inputSchema:
	      type: object
	      properties:
	        param1:
	          type: string
	    steps:
	      - id: step1
	        tool: some_tool
	        args:
	          arg1: "{{.param1}}"
	        store: result1

# Template Resolution

Workflow arguments support Go template syntax for variable substitution:
  - {{.param}} - Access input parameters
  - Simple string interpolation only (no complex logic)

# Permissions

Workflows have an agentModifiable flag that controls whether AI agents can modify them:
  - User workflows: agentModifiable defaults to false
  - Agent workflows: always agentModifiable

# Storage

Workflows are stored in two separate files:
  - ~/.envctl/workflows.yaml - User-defined workflows
  - ~/.envctl/agent_workflows.yaml - Agent-created workflows
*/
package workflow
```

## Acceptance Criteria
- [ ] README.md updated with workflow section
- [ ] Comprehensive workflow documentation created
- [ ] Example workflows covering common use cases
- [ ] Package documentation (doc.go)
- [ ] Integration with existing docs structure
- [ ] Clear examples for both users and agents
- [ ] Troubleshooting guide

## Dependencies
- All implementation issues (#50-#54) should be complete

## Labels
- documentation
- workflow
- examples
