### ISSUE TITLE
[META] Implement MCP Tool Workflows

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#56]
## Overview
This is a meta issue tracking the implementation of MCP Tool Workflows in envctl. This feature allows users and AI agents to define reusable sequences of MCP tool calls that are exposed as single tools through the aggregator.

## Background
The workflow system addresses the need for:
- Simplifying complex multi-step operations
- Reducing errors in repetitive tasks
- Enabling AI agents to create and improve their own automation patterns
- Providing higher-level abstractions for common operations

## Architecture Summary
```
┌─────────────┐     ┌──────────────────┐     ┌─────────────────┐
│   Agent     │────▶│   Aggregator     │────▶│  MCP Servers    │
│  (MCP       │     │                  │     │  - Kubernetes   │
│   Client)   │     │  ┌─────────────┐ │     │  - Prometheus   │
└─────────────┘     │  │  Workflow   │ │     │  - Teleport     │
                    │  │  Manager    │ │     │  - CAPI         │
                    │  └─────────────┘ │     │  - Flux         │
                    └──────────────────┘     └─────────────────┘
```

## Key Features
1. **Declarative Workflow Definition**: YAML-based workflow definitions with simple template support
2. **Agent Management**: Agents can create, update, and delete their own workflows
3. **Permission Control**: `agentModifiable` flag controls which workflows agents can modify
4. **Seamless Integration**: Workflows appear as regular MCP tools to clients
5. **Hot Reload**: Changes to workflow files are automatically detected

### Core Implementation
- [ ] #50 - Add workflow types and configuration structures
- [ ] #51 - Implement workflow storage and persistence
- [ ] #52 - Create workflow executor with template support
- [ ] #53 - Integrate workflow manager with aggregator
- [ ] #54 - Implement workflow management MCP tools

### Documentation
- [ ] #55 - Add workflow documentation and examples

### User-Defined Workflow
```yaml
workflows:
  - name: connect_cluster
    description: "Connect to a specific Teleport cluster"
    icon: "🔌"
    inputSchema:
      type: object
      properties:
        cluster:
          type: string
      required: ["cluster"]
    steps:
      - id: login
        tool: teleport_kube
        args:
          command: "login"
          cluster: "{{.cluster}}"
```

### Agent Usage
```
# List workflows
workflow.list({})

# Execute a workflow
workflow.connect_cluster({"cluster": "mymc-cluster1"})

# Create a new workflow
workflow.create({
  "name": "check_namespace",
  "description": "Check pods in a namespace",
  "steps": [{
    "id": "get_pods",
    "tool": "kubectl_get",
    "args": {
      "resourceType": "pods",
      "namespace": "{{.namespace}}"
    }
  }]
})
```

## Success Criteria
- [ ] Users can define workflows in YAML files
- [ ] Workflows are exposed as MCP tools through the aggregator
- [ ] Agents can discover and execute workflows
- [ ] Agents can create and modify their own workflows
- [ ] Template variables work correctly
- [ ] Errors are properly propagated
- [ ] Documentation is comprehensive
- [ ] Integration tests pass

## Timeline
Estimated completion: 2-3 weeks
- Week 1: Core implementation (#50-#53)
- Week 2: Management tools and testing (#54)
- Week 3: Documentation and polish (#55)

## Labels
- enhancement
- workflow
- meta
