### ISSUE TITLE
RFC: Transform envctl into MCP-driven capability coordination platform

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#59]
## Summary

Transform envctl from a monolithic orchestrator with hardcoded functionality (Teleport auth, port forwarding, etc.) into a capability coordination platform where MCP servers register and provide functionality.

## Motivation

Currently, envctl has hardcoded dependencies on Teleport for authentication and built-in port forwarding logic. This limits its use to Giant Swarm environments. By making these capabilities pluggable through MCP servers, we can:

1. Enable non-Giant Swarm users to use envctl with their own auth providers (AWS, GCP, kubeconfig)
2. Allow dynamic discovery and configuration without restarting envctl
3. Make the codebase more modular and testable
4. Enable community contributions of new capability providers

## Design Overview

```
┌─────────────────────────────────────────────────────────────────┐
│                        envctl (Coordination Platform)            │
│                                                                  │
│  ┌─────────────────┐  ┌──────────────────┐  ┌───────────────┐ │
│  │   Capability     │  │   Dependency     │  │   Service     │ │
│  │   Registry       │  │   Manager        │  │   Lifecycle   │ │
│  └─────────────────┘  └──────────────────┘  └───────────────┘ │
└─────────────────────────────────────────────────────────────────┘
                                   ▲
                                   │ Register Capabilities
                                   │
┌─────────────────┬─────────────────┬─────────────────┬──────────┐
│  Teleport MCP   │  Kubernetes MCP  │  Kubectl MCP    │  Custom  │
│                 │                  │                 │   MCPs   │
│ • Auth Provider │ • Discovery      │ • Port Forward  │          │
│ • Discovery     │ • Context Mgmt   │   Provider      │          │
└─────────────────┴─────────────────┴─────────────────┴──────────┘
```

### 1. Capability Types
- **auth_provider**: Handles cluster authentication
- **discovery_provider**: Discovers clusters and services  
- **portforward_provider**: Creates and manages port forwards
- **cluster_provider**: Manages cluster lifecycle (future)

### 2. Capability Registration
MCP servers register their capabilities when connecting:
```yaml
- tool: x_capability_register
  args:
    type: "auth_provider"
    name: "teleport"
    capabilities:
      - authenticate
      - refresh_token
      - list_clusters
```

### 3. Dynamic Service Creation
Services declare capability requirements instead of hardcoded dependencies:
```yaml
mcpServers:
  - name: prometheus
    requires:
      - capability: "port_forward"
        config:
          service: "prometheus"
          namespace: "monitoring"
      - capability: "auth"
        cluster_role: "workload"
```

### Phase 1: Capability Framework (Issues #1-3)
- Create capability registry and interfaces
- Implement capability registration tools
- Add capability-based dependency resolution

### Phase 2: Provider Migration (Issues #4-7)
- Extract Teleport auth into Teleport MCP
- Extract port forwarding into Kubectl MCP  
- Create Kubernetes discovery MCP
- Update existing services to use capabilities

### Phase 3: Dynamic Management (Issues #8-10)
- Implement dynamic service creation
- Add capability health monitoring
- Create user-facing tools for capability management

## Backwards Compatibility

- Existing configurations will be automatically migrated
- A compatibility layer will map old configs to capability requirements
- Users can opt-in to the new model gradually

## Success Criteria

1. Non-Giant Swarm users can use envctl with their own auth providers
2. Services can be created/modified without restarting envctl
3. New capability providers can be added without modifying core code
4. All existing functionality continues to work
5. Test coverage remains above 80%

## Related Issues

This is the parent issue for the capability registration feature. Implementation will be tracked in sub-issues.

**Labels:** enhancement, architecture, rfc
