### ISSUE TITLE
Create documentation and examples for capability-based architecture

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#67]
## Overview

Create comprehensive documentation and examples to help users understand and adopt the new capability-based architecture.

Part of #59
Depends on all implementation issues (#60-#66)

## Tasks

- [ ] Create architecture documentation
- [ ] Write capability provider development guide
- [ ] Create example configurations
- [ ] Document migration process
- [ ] Write troubleshooting guide
- [ ] Create quick start guides for common scenarios

### 1. Architecture Overview

Create `docs/architecture/capabilities.md`:

```markdown
# Capability-Based Architecture

## Overview

envctl has evolved from a monolithic orchestrator to a flexible capability coordination platform. This architecture enables:

- **Pluggable authentication**: Use Teleport, cloud providers, or custom auth
- **Dynamic service management**: Create/modify services without restart
- **Provider flexibility**: Replace any component with alternatives
- **Community extensions**: Easy to add new capabilities

## Core Concepts

### Capabilities

A capability represents a specific functionality that can be provided by an MCP server:

- **auth_provider**: Handles cluster authentication
- **discovery_provider**: Discovers clusters and services
- **portforward_provider**: Creates and manages port forwards
- **cluster_provider**: Manages cluster lifecycle (future)

### Capability Registration

MCP servers register their capabilities when they start:

\`\`\`javascript
await server.callTool('x_capability_register', {
  type: 'auth_provider',
  name: 'My Auth Provider',
  features: ['login', 'refresh', 'validate'],
  config: { /* provider-specific config */ }
});
\`\`\`

### Capability Requirements

Services declare what capabilities they need:

\`\`\`yaml
mcpServers:
  - name: prometheus
    capabilities:
      auth:
        type: required
        cluster_role: workload
      port_forwards:
        - name: prometheus-pf
          service: prometheus
          namespace: monitoring
\`\`\`

## How It Works

1. MCP servers start and register capabilities
2. Services declare capability requirements
3. Orchestrator matches requirements to providers
4. Dependencies are resolved dynamically
5. Services start when capabilities are available
```

### 2. Capability Provider Development Guide

Create `docs/guides/developing-capability-providers.md`:

```markdown
# Developing Capability Providers

## Overview

This guide shows how to create custom capability providers for envctl.

## Example: Custom Auth Provider

### 1. Create MCP Server

\`\`\`javascript
import { Server } from '@modelcontextprotocol/sdk/server/index.js';

const server = new Server({
  name: 'custom-auth-mcp',
  version: '1.0.0'
});

// Register capability on startup
server.on('initialize', async () => {
  await registerAuthCapability();
});
\`\`\`

### 2. Register Capability

\`\`\`javascript
async function registerAuthCapability() {
  const result = await server.callTool('x_capability_register', {
    type: 'auth_provider',
    name: 'Custom Auth Provider',
    description: 'Uses custom authentication method',
    features: ['login', 'validate', 'refresh'],
    config: {
      method: 'custom',
      endpoint: process.env.AUTH_ENDPOINT
    }
  });
  
  capabilityId = result.capability_id;
}
\`\`\`

### 3. Implement Required Tools

\`\`\`javascript
// Required for auth_provider
server.addTool({
  name: 'x_auth_login',
  description: 'Authenticate to cluster',
  inputSchema: {
    type: 'object',
    properties: {
      cluster: { type: 'string' }
    },
    required: ['cluster']
  }
}, async (params) => {
  // Your authentication logic here
  const token = await authenticateToCluster(params.cluster);
  
  // Update kubeconfig
  await updateKubeconfig(params.cluster, token);
  
  return {
    success: true,
    context_name: `custom-${params.cluster}`,
    expires_at: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString()
  };
});
\`\`\`

## Capability Provider Interfaces

### Auth Provider

Required tools:
- `x_auth_login(cluster)` - Authenticate to a cluster
- `x_auth_validate(context)` - Validate authentication status
- `x_auth_refresh(context)` - Refresh authentication

### Discovery Provider

Required tools:
- `x_discover_contexts()` - List available contexts
- `x_discover_clusters(context?)` - Get cluster information
- `x_discover_services(context, namespace?)` - Discover services

### Port Forward Provider

Required tools:
- `x_portforward_create(name, context, namespace, service, ports)`
- `x_portforward_stop(name)`
- `x_portforward_status(name)`
- `x_portforward_list()`
```

### 3. Example Configurations

Create `examples/` directory with various configurations:

#### `examples/teleport-setup.yaml`
```yaml
# Traditional Giant Swarm setup with Teleport
version: "2.0"

mcpServers:
  # Capability providers
  - name: teleport
    type: localCommand
    command: ["teleport-mcp"]
    enabled: true
    
  - name: kubectl
    type: localCommand
    command: ["kubectl-mcp"]
    enabled: true
    
  # Service MCPs
  - name: prometheus
    type: localCommand
    command: ["prometheus-mcp"]
    enabled: true
    capabilities:
      auth:
        cluster_role: workload
      port_forwards:
        - name: prometheus
          service: prometheus
          namespace: monitoring
          remotePort: 9090

clusters:
  - name: workload-cluster
    role: workload
    context: teleport.giantswarm.io-workload-cluster
```

#### `examples/cloud-provider-setup.yaml`
```yaml
# Setup for cloud provider authentication
version: "2.0"

mcpServers:
  # AWS auth provider
  - name: aws-auth
    type: localCommand
    command: ["aws-auth-mcp"]
    enabled: true
    env:
      AWS_REGION: us-east-1
      
  - name: kubectl
    type: localCommand
    command: ["kubectl-mcp"]
    enabled: true
    
  # Your services here
  - name: app-debugger
    type: localCommand
    command: ["app-debug-mcp"]
    capabilities:
      auth:
        cluster_role: production
      port_forwards:
        - name: app-db
          service: postgres
          namespace: app
          remotePort: 5432
```

#### `examples/minimal-kubeconfig.yaml`
```yaml
# Minimal setup using existing kubeconfig
version: "2.0"

mcpServers:
  # Kubernetes MCP provides discovery from kubeconfig
  - name: kubernetes
    type: localCommand
    command: ["kubernetes-mcp"]
    enabled: true
    
  # Simple port forward provider
  - name: kubectl
    type: localCommand  
    command: ["kubectl-mcp"]
    enabled: true

# Clusters will be discovered from kubeconfig
```

### 4. Migration Guide

Create `docs/guides/migration.md`:

```markdown
# Migration Guide

## From v1.x to v2.0

### Automatic Migration

Use the migration tool:

\`\`\`bash
envctl migrate-config
\`\`\`

This will:
1. Convert your existing config to capability-based format
2. Add required capability providers
3. Save to `envctl.migrated.yaml`

### Manual Migration

#### 1. Add Capability Providers

Add these MCP servers to your config:

\`\`\`yaml
mcpServers:
  - name: teleport
    type: localCommand
    command: ["teleport-mcp"]
    enabled: true
    
  - name: kubectl
    type: localCommand
    command: ["kubectl-mcp"]
    enabled: true
\`\`\`

#### 2. Update Service Dependencies

Replace old-style dependencies:

**Before:**
\`\`\`yaml
mcpServers:
  - name: prometheus
    requiresPortForwards:
      - prometheus-pf
    requiresClusterRole: workload
\`\`\`

**After:**
\`\`\`yaml
mcpServers:
  - name: prometheus
    capabilities:
      auth:
        cluster_role: workload
      port_forwards:
        - name: prometheus-pf
          service: prometheus
          namespace: monitoring
\`\`\`

## Breaking Changes

- `requiresPortForwards` → `capabilities.port_forwards`
- `requiresClusterRole` → `capabilities.auth.cluster_role`
- Port forward services are no longer created automatically
```

### 5. Troubleshooting Guide

Create `docs/guides/troubleshooting.md`:

```markdown
# Troubleshooting

## Common Issues

### No auth provider available

**Problem**: Services fail with "no auth provider available"

**Solution**: 
1. Ensure an auth provider MCP is configured and running
2. Check capability registration:
   \`\`\`bash
   envctl list-capabilities --type auth_provider
   \`\`\`

### Port forward not created

**Problem**: Port forwards not being created

**Solution**:
1. Verify port forward provider is running
2. Check service capability requirements
3. Ensure cluster authentication is working

## Debugging Tools

### List Registered Capabilities
\`\`\`bash
# Via MCP tool
x_capability_list

# Filter by type
x_capability_list --type portforward_provider
\`\`\`

### Check Service Dependencies
\`\`\`bash
# View service requirements
x_service_info prometheus

# Check if requirements are met
x_service_check_requirements prometheus
\`\`\`

### View Capability Providers
\`\`\`bash
# List all providers
x_capability_list

# Get provider details
x_capability_get <capability_id>
\`\`\`
```

### 6. Quick Start Guides

Create `docs/quickstart/` directory:

#### `docs/quickstart/non-giantswarm.md`
```markdown
# Quick Start for Non-Giant Swarm Users

## 1. Install envctl

\`\`\`bash
brew install giantswarm/tap/envctl
\`\`\`

## 2. Install Capability Providers

\`\`\`bash
# Core providers
npm install -g kubectl-mcp kubernetes-mcp

# Optional: cloud providers
npm install -g aws-auth-mcp    # For AWS
npm install -g gcp-auth-mcp    # For GCP
\`\`\`

## 3. Create Configuration

\`\`\`yaml
# envctl.yaml
version: "2.0"

mcpServers:
  - name: kubernetes
    type: localCommand
    command: ["kubernetes-mcp"]
    enabled: true
    
  - name: kubectl
    type: localCommand
    command: ["kubectl-mcp"]
    enabled: true
\`\`\`

## 4. Start envctl

\`\`\`bash
envctl start
\`\`\`

## 5. Discover and Use Clusters

Clusters from your kubeconfig are automatically available!
```

## Testing Requirements

1. All documentation examples must be tested
2. Code examples must compile/run
3. Configuration examples must be valid
4. Migration tool must handle all v1.x configs
5. Quick start guides must work end-to-end

## Acceptance Criteria

- [ ] Architecture documentation is clear and complete
- [ ] Provider development guide includes working examples
- [ ] All common scenarios have example configurations
- [ ] Migration guide covers all breaking changes
- [ ] Troubleshooting guide addresses common issues
- [ ] Quick start guides work for new users
- [ ] All documentation is reviewed and tested

## Dependencies

All implementation issues must be completed first.

## Estimated Effort

2-3 days
