### ISSUE TITLE
Task 14: Create Comprehensive YAML Test Scenarios Based on Behavioral Documentation

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#89]
# Task 14: Create Comprehensive YAML Test Scenarios Based on Behavioral Documentation

**Parent Issue**: [#69 - Epic: envctl Testing & Hardening](https://github.com/giantswarm/envctl/issues/69)

## Objective
Transform the extensive behavioral scenarios documentation into executable YAML test scenarios that can be run by the `envctl test` framework.

## Context
We have comprehensive behavioral scenarios documented in `/docs/behavioral-scenarios/` covering all core concepts (ServiceClass, Workflow, MCPServer, Capability, Service management). These scenarios provide detailed test steps, expected behaviors, and validation patterns that need to be converted into structured YAML test scenarios.

## Source Documentation
- `docs/behavioral-scenarios/serviceclass-management.md` (466 lines, 7 scenarios)
- `docs/behavioral-scenarios/workflow-management.md` (503 lines, 7 scenarios)
- `docs/behavioral-scenarios/mcpserver-management.md` (471 lines, 8 scenarios)
- `docs/behavioral-scenarios/capability-management.md` (485 lines, 8 scenarios)
- `docs/behavioral-scenarios/service-management.md` (298 lines, 6 scenarios)

**Total**: 2,200+ lines of comprehensive behavioral documentation

## Related Subtasks
- [ ] [#90 - Subtask 14.1: ServiceClass Test Scenarios Implementation](https://github.com/giantswarm/envctl/issues/90)
- [ ] [#91 - Subtask 14.2: Workflow Test Scenarios Implementation](https://github.com/giantswarm/envctl/issues/91)
- [ ] [#92 - Subtask 14.3: MCPServer Test Scenarios Implementation](https://github.com/giantswarm/envctl/issues/92)
- [ ] [#93 - Subtask 14.4: Capability Test Scenarios Implementation](https://github.com/giantswarm/envctl/issues/93)
- [ ] [#94 - Subtask 14.5: Service Test Scenarios Implementation](https://github.com/giantswarm/envctl/issues/94)
- [ ] [#95 - Subtask 14.6: Integration Test Scenarios](https://github.com/giantswarm/envctl/issues/95)
- [ ] [#96 - Subtask 14.7: Error Handling and Edge Case Scenarios](https://github.com/giantswarm/envctl/issues/96)

## YAML Test Scenario Structure

```yaml
name: "scenario-name"
category: "behavioral"  # behavioral | integration
concept: "serviceclass"  # serviceclass | workflow | mcpserver | capability | service
description: "Human-readable description"
timeout: "5m"
tags: ["basic", "crud"]

steps:
  - name: "step-name"
    description: "Step description"
    tool: "core_serviceclass_create"
    parameters:
      yaml: |
        # YAML content for tool
    expected:
      success: true
      contains: ["success", "created"]
      json_path:
        status: "created"
    timeout: "1m"
    retry:
      count: 3
      delay: "5s"

cleanup:
  - name: "cleanup-step"
    # ... similar structure
```

## Success Criteria
- [ ] **100+ YAML test scenarios** across all core concepts
- [ ] **ServiceClass Scenarios**: 20+ YAML scenarios covering all documented behaviors
- [ ] **Workflow Scenarios**: 15+ YAML scenarios covering workflow lifecycle and execution
- [ ] **MCPServer Scenarios**: 15+ YAML scenarios covering server management and tool integration
- [ ] **Capability Scenarios**: 15+ YAML scenarios covering operation execution and dependencies
- [ ] **Service Scenarios**: 20+ YAML scenarios covering service ecosystem and lifecycle
- [ ] **Integration Scenarios**: 10+ YAML scenarios covering cross-concept interactions
- [ ] **Error Handling**: 15+ YAML scenarios covering comprehensive error scenarios
- [ ] **Test Coverage**: All scenarios executable via `envctl test` command
- [ ] **Documentation**: Updated test documentation with scenario structure

## Dependencies
- ✅ Task 13: Test Framework Architecture (completed)
- ✅ Behavioral scenarios documentation (available in `/docs/behavioral-scenarios/`)
- Live system validation via mcp-debug tools

## Implementation Timeline
**Estimated Effort**: 100+ YAML test scenarios across all core concepts

## Labels
- `epic:testing-hardening`
- `task`
- `component:testing`
- `priority:high`
