### ISSUE TITLE
Task 15: Implement Mock MCP Server for Safe Behavioral Testing

### ISSUE THREAD

**Issue by teemow** [giantswarm/envctl#97]
# Task 15: Implement Mock MCP Server for Safe Behavioral Testing

**Parent Issue**: [#69 - Epic: envctl Testing & Hardening](https://github.com/giantswarm/envctl/issues/69)

## Problem Statement
Behavioral tests for envctl need to test the functionality to manage and aggregate MCP servers, but using real MCP servers in tests can:
- Automate external APIs and perform harmful actions
- Create resources that are difficult to clean up
- Have unpredictable side effects that affect test reliability
- Require complex external dependencies that may not be available in CI

For comprehensive behavioral testing, we need a configurable mock MCP server that can be controlled and safely used in test scenarios.

## Objective
Create a configurable mock MCP server implementation within envctl that can be started as a process and used for behavioral testing of all envctl concepts (MCPServers, ServiceClasses, Workflows, Capabilities, Services).

### Mock MCP Server Features
- **Process-based**: Can be started as a separate process like real MCP servers
- **Configurable Tools**: Support defining custom tool schemas and responses
- **Safe Execution**: All tool calls are simulated - no real external API calls
- **Test Integration**: Seamless integration with `envctl test` command
- **Flexible Responses**: Support for success, error, and timeout scenarios
- **State Tracking**: Optional state tracking for stateful test scenarios

### Command Integration
```bash
# Start standalone mock MCP server for testing
envctl test --mock-mcpserver --config=mock-server-config.yaml

# Run tests using mock MCP server
envctl test --use-mock-server --mock-config=test-mocks.yaml
```

### Configuration Structure
```yaml
# Mock MCP Server Configuration
name: "test-mock-server"
tools:
  - name: "kubectl_get_pods"
    description: "Mock kubectl get pods"
    inputSchema:
      type: "object"
      properties:
        namespace:
          type: "string"
          default: "default"
    responses:
      success:
        pods:
          - name: "test-pod-1"
            status: "Running"
          - name: "test-pod-2"
            status: "Pending"
      error:
        message: "Namespace not found"
        code: 404
  - name: "prometheus_query"
    description: "Mock Prometheus query"
    inputSchema:
      type: "object"
      properties:
        query:
          type: "string"
          required: true
    responses:
      success:
        data:
          result:
            - metric: {__name__: "cpu_usage"}
              value: [1640995200, "0.75"]
```

## Related Subtasks
- [ ] [#97 - Subtask 15.1: Design Mock MCP Server Architecture and Core Engine](#97)
- [ ] [#98 - Subtask 15.2: Implement Tool Configuration System](#98) 
- [ ] [#99 - Subtask 15.3: Build Response Engine with Success/Error/Timeout Scenarios](#99)
- [ ] [#100 - Subtask 15.4: Integrate Mock Server with envctl test Command](#100)
- [ ] [#101 - Subtask 15.5: Create Predefined Mock Configurations for Test Scenarios](#101)
- [ ] [#102 - Subtask 15.6: Implement State Tracking for Stateful Test Scenarios](#102)
- [ ] [#103 - Subtask 15.7: Documentation and Usage Examples](#103)

### Core Components
1. **Mock Server Engine**: MCP protocol-compliant server implementation
2. **Tool Configuration System**: YAML-based tool and response definitions
3. **Response Engine**: Configurable success/error/timeout response handling
4. **Process Management**: Integration with envctl service management
5. **Test Integration**: Seamless `envctl test` command integration
6. **State Management**: Optional stateful behavior for complex scenarios

### Integration Points
- **Test Framework**: Integrate with existing `envctl test` command
- **Service Management**: Use existing process management infrastructure
- **Configuration System**: Leverage existing YAML configuration patterns
- **MCP Protocol**: Implement full MCP server compliance

### 1. ServiceClass Testing
```yaml
# Test ServiceClass that depends on kubernetes tools
serviceClass:
  name: "test-k8s-service"
  tools: ["kubectl_get_pods", "kubectl_create_deployment"]
  
mockServer:
  tools:
    kubectl_get_pods: {success: {pods: []}}
    kubectl_create_deployment: {success: {deployment: "created"}}
```

### 2. Workflow Testing
```yaml
# Test workflow with multiple tool calls
workflow:
  steps:
    - tool: "prometheus_query"
      args: {query: "cpu_usage"}
    - tool: "kubectl_create_configmap"
      args: {name: "alert-config"}
      
mockServer:
  tools:
    prometheus_query: {success: {data: {result: []}}}
    kubectl_create_configmap: {success: {configmap: "created"}}
```

### 3. Error Scenario Testing
```yaml
# Test error handling
mockServer:
  tools:
    kubectl_get_pods:
      error: {message: "Connection refused", code: 500}
    prometheus_query:
      timeout: {duration: "5s"}
```

## Implementation Location
- **Package**: `internal/testing/mock/`
- **Command Integration**: Extend `cmd/test.go`
- **Configuration**: `internal/testing/mock/config.go`
- **Server Engine**: `internal/testing/mock/server.go`
- **Response Engine**: `internal/testing/mock/responses.go`

## Acceptance Criteria
- [ ] **Mock MCP server** can be started as standalone process
- [ ] **Tool configuration** via YAML with custom schemas and responses
- [ ] **Full MCP protocol compliance** for tool listing and execution
- [ ] **Response scenarios** support (success, error, timeout)
- [ ] **Test integration** with `envctl test --mock-mcpserver` flag
- [ ] **Predefined configurations** for common test scenarios
- [ ] **State tracking** for stateful test scenarios (optional)
- [ ] **Documentation** with usage examples and configuration reference
- [ ] **Zero external dependencies** - all responses are simulated
- [ ] **CI/CD integration** - reliable and deterministic test execution

## Dependencies
- ✅ Test framework architecture (Task 13)
- ✅ MCP protocol implementation patterns
- Live system testing via mcp-debug for validation

## Success Metrics
- Mock MCP server supports 20+ configurable tools
- 100% test reliability with zero external dependencies
- <1 second startup time for mock server
- Integration with all existing test scenarios
- Support for complex multi-step workflows in tests

## Labels
- `epic:testing-hardening`
- `task`
- `component:testing`
- `component:mcpserver`
- `priority:high`

---
**Epic:** [#69 - envctl Testing & Hardening](https://github.com/giantswarm/envctl/issues/69)  
**Complexity:** 8/10
